name: Main Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: container image tag
        default: dev
jobs: 
  containerize:
    name: Upload Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: Build and Push (Dev)
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"
          build-args: |
          tags: "mannkind/meshtastic2mqtt:dev"
        
      - name: Build and Push (Main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"
          build-args: |
          tags: "mannkind/meshtastic2mqtt:latest,ghcr.io/mannkind/meshtastic2mqtt:latest"
